---
AllCops:
  TargetRubyVersion: 2.7.1

Style/Documentation:
  Exclude:
    - '**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - '*.gemspec'
    - 'Rakefile'
    - 'bin/**/*'
